# Stage 1: Build Stage
FROM node:18.18.2-bullseye-slim AS builder

WORKDIR /app

# Define build arguments for environment variables
ARG NODE_ENV="production"
ARG VITE_APP_FIREBASE_API_KEY
ARG VITE_APP_FIREBASE_AUTH_DOMAIN
ARG VITE_APP_FIREBASE_PROJECT_ID
ARG VITE_APP_FIREBASE_STORAGE_BUCKET
ARG VITE_APP_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_APP_FIREBASE_APP_ID
ARG VITE_APP_FIREBASE_MEASUREMENT_ID

# Create the .env file with the ARG values
RUN echo "NODE_ENV=$NODE_ENV" >> .env && \
    echo "VITE_APP_FIREBASE_API_KEY=$VITE_APP_FIREBASE_API_KEY" >> .env && \
    echo "VITE_APP_FIREBASE_AUTH_DOMAIN=$VITE_APP_FIREBASE_AUTH_DOMAIN" >> .env && \
    echo "VITE_APP_FIREBASE_PROJECT_ID=$VITE_APP_FIREBASE_PROJECT_ID" >> .env && \
    echo "VITE_APP_FIREBASE_STORAGE_BUCKET=$VITE_APP_FIREBASE_STORAGE_BUCKET" >> .env && \
    echo "VITE_APP_FIREBASE_MESSAGING_SENDER_ID=$VITE_APP_FIREBASE_MESSAGING_SENDER_ID" >> .env && \
    echo "VITE_APP_FIREBASE_APP_ID=$VITE_APP_FIREBASE_APP_ID" >> .env && \
    echo "VITE_APP_FIREBASE_MEASUREMENT_ID=$VITE_APP_FIREBASE_MEASUREMENT_ID" >> .env

# Install dependencies and build the Vite app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Production Stage
FROM nginx:alpine

# Copy the built files from the builder stage to Nginx's HTML folder
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy SSL certificates from the host
# COPY /etc/letsencrypt/live/tasks-tracker.online/fullchain.pem /etc/nginx/ssl/fullchain.pem
# COPY /etc/letsencrypt/live/tasks-tracker.online/privkey.pem /etc/nginx/ssl/privkey.pem

# Expose HTTP and HTTPS ports
EXPOSE 80 443

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
