version: "3"

services:
  react-vite-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  python-flask-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/code/app
    ports:
      - 8000:8000
    restart: on-failure
