version: "3"

services:
  react-vite-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: ${NODE_ENV}
        VITE_APP_FIREBASE_API_KEY: ${VITE_APP_FIREBASE_API_KEY}
        VITE_APP_FIREBASE_AUTH_DOMAIN: ${VITE_APP_FIREBASE_AUTH_DOMAIN}
        VITE_APP_FIREBASE_PROJECT_ID: ${VITE_APP_FIREBASE_PROJECT_ID}
        VITE_APP_FIREBASE_STORAGE_BUCKET: ${VITE_APP_FIREBASE_STORAGE_BUCKET}
        VITE_APP_FIREBASE_MESSAGING_SENDER_ID: ${VITE_APP_FIREBASE_MESSAGING_SENDER_ID}
        VITE_APP_FIREBASE_APP_ID: ${VITE_APP_FIREBASE_APP_ID}
        VITE_APP_FIREBASE_MEASUREMENT_ID: ${VITE_APP_FIREBASE_MEASUREMENT_ID}
        VITE_APP_BACKEND_URL: ${VITE_APP_BACKEND_URL}
    depends_on:
      - fastapi-backend
    restart: unless-stopped
    expose:
      - "5173" # Ensure the frontend service exposes the correct port

  #Needs testing
  fastapi-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    args:
      - ENV=production
      - BACKEND_FIREBASE_TYPE=${BACKEND_FIREBASE_TYPE}
      - BACKEND_FIREBASE_PROJECT_ID=${BACKEND_FIREBASE_PROJECT_ID}
      - BACKEND_FIREBASE_PRIVATE_KEY_ID=${BACKEND_FIREBASE_PRIVATE_KEY_ID}
      - BACKEND_FIREBASE_PRIVATE_KEY=${BACKEND_FIREBASE_PRIVATE_KEY}
      - BACKEND_FIREBASE_CLIENT_EMAIL=${BACKEND_FIREBASE_CLIENT_EMAIL}
      - BACKEND_FIREBASE_CLIENT_ID=${BACKEND_FIREBASE_CLIENT_ID}
      - BACKEND_FIREBASE_AUTH_URI=${BACKEND_FIREBASE_AUTH_URI}
      - BACKEND_FIREBASE_TOKEN_URI=${BACKEND_FIREBASE_TOKEN_URI}
      - BACKEND_FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${BACKEND_FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
      - BACKEND_FIREBASE_CLIENT_X590_CERT_URL=${BACKEND_FIREBASE_CLIENT_X590_CERT_URL}
      - BACKEND_FIREBASE_UNIVERSE_DOMAIN=${BACKEND_FIREBASE_UNIVERSE_DOMAIN}
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - fastapi_data:/app/data
      - uploads-data:/code/app/uploads

  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      # - /root/Caddyfile:/etc/caddy/Caddyfile
      - ./Caddyfile:/etc/caddy/Caddyfile # Use relative path to map local Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  fastapi_data:
  uploads-data:
