FROM python:3.12.7

# WORKDIR /code

# COPY ./requirements.txt /code/requirements.txt

# RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# COPY . .

# CMD ["fastapi", "run", "app/main.py", "--port", "80"]


FROM python:3.12.7
WORKDIR /code
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["uvicorn", "code.main:app", "--host", "0.0.0.0", "--port", "8000"]