export const DEFAULT_ITEMS_PER_PAGE = 15;
export const DEFAULT_READ_PROJECT_ITEMS_PER_PAGE = 15;
export const DEFAULT_PAGE_NUMBER = 1;
export const AVAILABLE_ITEMS_PER_PAGE = [15, 25, 50];
export const ITEMS_PER_PAGE = "items_per_page";
export const PAGE_NUMBER = "page";

// Configuration name for sessions filters array
export const SESSION_FILTERS_ARRAY_CONFIG_NAME = "FILTERS";
export const FILTERS_SET = "filters_set";

export const MAX_PAGE_NUMBERS_TO_SHOW = 6;

export const LAST_VISITED_PAGE_NUMBER_KEY = "LAST_VISITED";
export const ALLOWED_ITEMS_PER_PAGE = [15, 25, 50];


//TASKS
export const SELECTED_TASK = "SELECTED_TASK";
export const LAST_TASK_OBJECT = "LAST_TASK_OBJECT";
export const TASKS_PRIORITY = {
    LOW: 0,
    MEDIUM: 1,
    HIGH: 2,
}

export const TASKS_STATUS = {
    TODO: 0,
    IN_PROGRESS: 1,
    COMPLETED: 2,
}

export const TASKS_BOARD_HEADERS = [
    { id: 1, name: "Todo", status: TASKS_STATUS.TODO, },
    { id: 2, name: "Doing", status: TASKS_STATUS.IN_PROGRESS },
    { id: 3, name: "Done", status: TASKS_STATUS.COMPLETED }
]
//filters session
export const SESSION_THEME_MODE = "SESSION_THEME_MODE";
export const TASKS_ARCHIVED_SESSION_FILTER = "TASKS_ARCHIVED_SESSION_FILTER";


//tasks status
export const TODO_STATUS_TASKS_SESSION_FILTER = "TODO_STATUS_TASKS_SESSION_FILTER";
export const IN_STATUS_PROGRESS_TASKS_SESSION_FILTER = "IN_STATUS_PROGRESS_TASKS_SESSION_FILTER";
export const COMPLETED_STATUS_TASKS_SESSION_FILTER = "COMPLETED_STATUS_TASKS_SESSION_FILTER";

//tasks priority
export const LOW_PRIORITY_TASKS_SESSION_FILTER = "LOW_PRIORITY_TASKS_SESSION_FILTER";
export const MEDIUM_PRIORITY_TASKS_SESSION_FILTER = "MEDIUM_PRIORITY_TASKS_SESSION_FILTER";
export const HIGH_PRIORITY_TASKS_SESSION_FILTER = "HIGH_PRIORITY_TASKS_SESSION_FILTER";


//DEFAULTS
export const DEFAULT_PROJECT_ID = 0;
export const MAX_BOARD_ITEMS = 50;
export const DEFAULT_TASKS_ARCHIVE = false;


